const conditionalOperators = ['==', '!=', '<', '<=', '>', '>='];

const predefinedVariables = {
    countries: ['countryId', 'region', 'baseUrl', 'attempts'],
    document: ['front_imagePath', 'back_imagePath', 'documentId', 'front', 'back', 'longitude', 'latitude', 'front_attemptsCount', 'back_attemptsCount', 'attempts', 'front_submittedTimestamp', 'back_submittedTimestamp'],
    face: ['croppedImagePath', 'fullImagePath', 'videoPath', 'longitude', 'latitude', 'attemptsCount', 'attempts', 'submittedTimestamp'],
    form: ['btnPositiveClicked', 'btnNegativeClicked', 'attempts'], // deprecated
    dynamicForm: ['attempts'],
    dynamicFormV2: ['attempts'],
    barcode: ['barcodeData', 'barcodeStatus', 'attempts'],
    webview: ['attempts'],
    api: ['attempts', 'state', 'status'],
    videoStatement: ['pass', 'image', 'statements', 'attempts'],
    videoStatementV2: ['imagePath', 'videoPath', 'statement', 'videoUrl', 'attemptsCount', 'attempts'],
    nfc: ['nfcData', 'nfcStatus', 'attempts', 'nfcErrorMessage', 'nfcErrorCode', 'nfcLastStep'],
  };

  const formComponentsExposedVariables = {
    label: [],
    radio: ["value"],
    vertical: ["enabled", "visible", "value"],
    horizontal: ["enabled", "visible", "value"],
    button: ["value", "enabled", "visible"],
    checkbox: ["isValid", "value", "enabled", "required", "visible"],
    date: ["isValid", "value", "enabled", "required", "visible"],
    dropdown: ["isValid", "value", "enabled", "required", "visible"],
    text: ["isValid", "value", "enabled", "required", "visible"],
    file: [
      "isValid",
      "value",
      "totalSize",
      "totalSizeLabel",
      "numberOfFiles",
      "imagesPicked",
      "documentsPicked",
    ],
    image: [],
    divider: [],
    loader: [],
    chip: [],
    timer: ["state", "valueSeconds", "valueMinutes", "valueHours", "isValid", "value", "enabled", "required", "visible", ],
    list: ["value",],
  };

  const predefinedInputVariables = ['appId', 'appKey', 'transactionId', 'workflowId', 'accessToken', ];

  const predefinedSdkVariables = ['platform', 'device'];
  // TODO: Implement subtype validation based on specific types
  const validSubTypes = [
    // global
    "id_card_validation",
    "poa_validation",
    "selfie_validation",
    "countries",
    "form", "formV2",
    "selfie_id_match_api",
    "text_match_api",
    "selfie_selfie_match_api",
    "ip_geolocation_api",
    "dedupe_api",
    "aml_search_api",
    "face_auth_api",
    "phl_dedupe_search_api",
    "face_dedupe_api",
    "barcode_verification", // deprecated
    "barcode",
    "convert_api",
    "data_logging",
    "kyc_databasecheck_api",
    "age_from_dob_api",
    "start_session",
    "stop_session",
    "videoStatement",
    "video_otp_verification",
    "video_kyc_user_link_api",
    "video_kyc_verification_info_api",
    "video_kyc_image_upload_api",
    "video_statement",
    "vn_qr_thomas_api",
    "vnid_nfc_read_card",
    "vnid_nfc_verify",
    "vnid_nfc_signature",
    "nfc_verify",
    "verify_expiry",
    "genericApiV1",
    "genericWebviewV1",
    "genericChildApiV1",
    "face_match_api",
    "face_match_v2",
    "nfc",
    "shopfront_api",
    // India
    "ind_epfo_otp_send_api",
    "ind_epfo_otp_verify_api",
    "ind_ckyc_search_api",
    "ind_ckyc_download_api",
    "ind_ckyc_upload_api",
    "ind_ckyc_validate_api",
    "ind_name_split_api",
    "ind_json_to_string_api",
    "ind_webview_pan_form",
    "ind_digilocker_form",
    "ind_digilocker_flow",
    "digilocker_form",
    "aadhaar_xml_form",
    "aa_webview",
    "aa_fi_fetch_api",
    "aa_consent_request_api",
    "aa_polling_webview",
    "redirect_webview", // is this required?
    "ind_okyc_form",
    "ind_okyc_flow",
    "ind_central_db_checks_api",
    "ind_penny_drop_api",
    "ind_udyam_ocr_api",
    "ind_gst_ocr_api",
    "ind_shop_est_ocr_api",
    "ind_gst_auth_api",
    "ind_kyb_gst_verification",
    "ind_kyb_cin_verification",
    "ind_currentAddress_form",
    "ind_tds_api",
    "ind_credit_card_api",
    "ind_pan_lite_api",
    "upi_webview",
    "ind_pennyless_api",
    "cheque_capture",
    "cheque_ocr_api",
    "mobile_otp_send_api",
    "mobile_otp_verify_api",
    "prefill_pan_api",
    "ind_search_bank",
    "ind_search_bank_ifsc",
    //USA
    "usa_ssn_verification",
    "usa_dl_verification",
    "usa_address_dob_verification",
    // Nigeria
    "nga_bvn_check_api",
  ];

module.exports = {
    conditionalOperators,
    predefinedVariables,
    formComponentsExposedVariables,
    predefinedInputVariables,
    predefinedSdkVariables,
    validSubTypes,
}