const warnings = {
    MISSING_VALIDATION_FOR_COMPONENT: 'MISSING_VALIDATION_FOR_COMPONENT',
    INVALID_ONVALIDATED_FOR_LABEL: 'INVALID_ONVALIDATED_FOR_LABEL',
    EMPTY_ONVALIDATED: 'EMPTY_ONVALIDATED',
    REGEX_VALIDATION_NOT_FOUND: 'REGEX_VALIDATION_NOT_FOUND',
    EMPTY_FIELD_VALUE: 'EMPTY_FIELD_VALUE',
    EMPTY_REQUEST_PARAMETER_OR_BODY: 'EMPTY_REQUEST_PARAMETER_OR_BODY',
    MISSING_NULL_CHECK_IN_RULE: 'MISSING_NULL_CHECK_IN_RULE',
    EMPTY_IF_TRUE_OR_IF_FALSE_CONDITIONAL: 'EMPTY_IF_TRUE_OR_IF_FALSE_CONDITIONAL',
    SUBSTRING_FOUND_IN_ID: 'SUBSTRING_FOUND_IN_ID', // moving substring to warnings temporarily
    DEPRECATED_MODULE: 'DEPRECATED_MODULE',
    INVALID_ONCHANGE_FOR_LIST: 'INVALID_ONCHANGE_FOR_LIST',
    INVALID_NUMBEROFCOLUMNS: 'INVALID_NUMBEROFCOLUMNS',
    EMPTY_SDK_RESPONSE: 'EMPTY_SDK_RESPONSE', 
    UNVISITED_NODE: 'UNVISITED_NODE',
    INVALID_NEXT_STEP: 'INVALID_NEXT_STEP',
};

module.exports = {
    warnings,
}